---
title: Teknoloji Forumu
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day-:title/"
paginate: 10
markdown: kramdown
encoding: utf-8
author:
  name: Admin
  email: ismetceberr@gmail.com
  link: https://tekno-blog.vercel.app
  weibo: https://tekno-blog.vercel.app
  github: https://github.com/SaitamaR10
  zhihu: https://www.zhihu.com/people/JimmyLv
  juejin: https://juejin.im/user/5628752900b07a1836200154
  stackoverflow: https://stackoverflow.com/users/5871340/jimmylv
description: TeknolojiForumu
url: https://blog.jimmylv.info
repo: https://github.com/saitamar10/tekno-blog
rss: "/pages/atom.xml"
gavatar: "/public/img/gavatar.jpg"
favicon: "/public/img/favicon.ico"
ga:
  id: UA-74789926-1
  url: https://tekno-blog.vercel.app
disqus:
  shortname: gotoshare
active: Aktif
cates:
- React
- PKM
locals:
  english: English
  video: Video
  notes: Notlar
  ideas: Fikirler
  tags: Etiketler
  about: Hakkımızda
  newest: Haberler
  archive: Arşiv
  search: Ara
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll/tagging
- jekyll-tagging-related_posts
- jekyll-seo-tag
- jekyll-mermaid
- jekyll-twitter-plugin
exclude:
- ".idea/"
- ".github/"
- ".travis/"
- node_modules/
- vendor
- themes/
- _posts/演讲/assets
